// Sample Scanners Data

// Because of the API Limits I will use this data to mimic data fetch:

/* API Limits:
 *  In order to continue to offer free services to everyone,
 *  our members with the free users can make limited (10 for now) request per day.
 *  All API requests count are reset at 00:00 UTC(+0).
 * */

export const scannersData = [
  {
    name: "Fortinet FortiDDoS Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:24:51.217288",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the use of Fortinet FortiDDoS Certificate in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiDDoS Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortiddos-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Fortinet FortiManager Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:24:35.444046",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the use of Fortinet FortiManager Certificate in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiManager Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortimanager-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Fortinet FortiAuthenticator Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:24:08.135563",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the use of Fortinet FortiAuthenticator Certificate in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiAuthenticator Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortiauthenticator-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Fortinet FortiWifi Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:25:13.436194",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the certificate of Fortinet FortiWiFi in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiWifi Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortiwifi-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Fortinet FortiGate Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:25:30.674249",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the certificate of Fortinet FortiGate in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiGate Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortigate-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Fortinet FortiAnalyzer Certificate Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:25:52.401158",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the certificate of Fortinet FortiAnalyzer in digital assets.",
    user_id: null,
    meta_title: "Fortinet FortiAnalyzer Certificate Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fortianalyzer-certificate-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "CVE-2020-15906 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:10:30.666751",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2020-15906 Scanner - Authentication Bypass vulnerability in Tiki Wiki CMS GroupWare",
    user_id: null,
    meta_title:
      "CVE-2020-15906 Scanner - Authentication Bypass vulnerability in Tiki Wiki CMS GroupWare",
    asset_type: "domain,ipv4",
    slug: "tiki-wiki-cms-groupware-authentication-bypass-cve-2020-15906",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-11728 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:10:08.905076",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-11728 Scanner - SQL Injection vulnerability in KiviCare Clinic & Patient Management System",
    user_id: null,
    meta_title:
      "CVE-2024-11728 Scanner - SQL Injection vulnerability in KiviCare Clinic & Patient Management System",
    asset_type: "domain,ipv4",
    slug: "kivicare-sql-injection-cve-2024-11728",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-11303 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:09:53.265478",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-11303 Scanner - Path Traversal vulnerability in Korenix JetPort 5601",
    user_id: null,
    meta_title:
      "CVE-2024-11303 Scanner - Path Traversal vulnerability in Korenix JetPort 5601",
    asset_type: "url",
    slug: "korenix-jetport-5601-path-traversal-cve-2024-11303",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-55956 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:09:28.474636",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-55956 Scanner - Unrestricted File Upload vulnerability in Cleo Harmony",
    user_id: null,
    meta_title:
      "CVE-2024-55956 Scanner - Unrestricted File Upload vulnerability in Cleo Harmony",
    asset_type: "domain,ipv4",
    slug: "cleo-harmony-unrestricted-file-upload-cve-2024-55956",
    estimate_time: 10,
  },
  {
    name: "EasyCVR Video Management Arbitrary File Read Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:26:08.830309",
    auto_desc: "",
    protocol_id: 120,
    score: 6.3,
    mini_desc:
      "Detects 'Arbitrary File Read' vulnerability in EasyCVR Video Management.",
    user_id: null,
    meta_title:
      "EasyCVR Video Management Arbitrary File Read Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "easycvr-video-management-arbitrary-file-read-vulnerability",
    estimate_time: 10,
  },
  {
    name: "Infinitt PACS System Arbitrary File Upload Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-31T12:26:25.528843",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "Detects 'Arbitrary File Upload' vulnerability in Infinitt PACS System.",
    user_id: null,
    meta_title:
      "Infinitt PACS System Arbitrary File Upload Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "infinitt-pacs-system-arbitrary-file-upload-vulnerability",
    estimate_time: 10,
  },
  {
    name: "X-HTTP-Method-Override Security Misconfiguration Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-19T14:06:00",
    auto_desc: "",
    protocol_id: 120,
    score: 5,
    mini_desc:
      "This scanner detects the use of the X-HTTP-Method-Override header security misconfiguration in digital assets. It identifies systems that improperly honor this header, which could lead to unexpected behavior and vulnerabilities.",
    user_id: null,
    meta_title: "X-HTTP-Method-Override Security Misconfiguration Scanner",
    asset_type: "url",
    slug: "x-http-method-override-security-misconfiguration-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "CVE-2023-6697 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:09:12.061330",
    auto_desc: "",
    protocol_id: 120,
    score: 6.1,
    mini_desc:
      "CVE-2023-6697 Scanner - Cross-Site Scripting vulnerability in WP Go Maps",
    user_id: null,
    meta_title:
      "CVE-2023-6697 Scanner - Cross-Site Scripting vulnerability in WP Go Maps",
    asset_type: "domain,ipv4",
    slug: "wp-go-maps-cross-site-scripting-cve-2023-6697",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-24116 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:08:50.811932",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-24116 Scanner - Improper Authentication vulnerability in Ruijie RG-NBS2009G-P",
    user_id: null,
    meta_title:
      "CVE-2024-24116 Scanner - Improper Authentication vulnerability in Ruijie RG-NBS2009G-P",
    asset_type: "url",
    slug: "ruijie-rg-nbs2009g-p-improper-authentication-cve-2024-24116",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-36404 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-25T08:08:23.465619",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-36404 Scanner - Remote Code Execution vulnerability in GeoServer",
    user_id: null,
    meta_title:
      "CVE-2024-36404 Scanner - Remote Code Execution vulnerability in GeoServer",
    asset_type: "domain,ipv4",
    slug: "geoserver-remote-code-execution-CVE-2024-36404",
    estimate_time: 10,
  },
  {
    name: "Siemens WINCC Server Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Siemens WINCC Server in digital assets. It provides insights into the presence of the SCADA system for enhanced network visibility.",
    user_id: null,
    meta_title: "Siemens WINCC Server Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "siemens-wincc-server-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Siemens S7 PLC Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the presence of Siemens S7 PLC devices in digital assets. It collects device-specific information like hardware, version, and system name to aid in inventory and security management.",
    user_id: null,
    meta_title: "Siemens S7 PLC Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "siemens-s7-plc-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "ProConOS Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc: "This scanner detects the use of ProConOS in digital assets.",
    user_id: null,
    meta_title: "ProConOS Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "proconos-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "PCWorx Protocol Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of PCWorx Protocol by Phoenix Contact in digital assets.",
    user_id: null,
    meta_title: "PCWorx Protocol Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "pcworx-protocol-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "OMRON FINS Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of OMRON FINS Technology in digital assets.",
    user_id: null,
    meta_title: "OMRON FINS Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "omron-fins-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Moxa NPort Series Serial Device Servers Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Moxa NPort Series Serial Device Servers and their configuration settings in digital assets.",
    user_id: null,
    meta_title: "Moxa NPort Series Serial Device Servers Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "moxa-nport-series-serial-device-servers-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Modbus SCADA Devices Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Modbus SCADA Devices in digital assets. It identifies device information, including vendor and firmware details, to help understand the deployment and configuration.",
    user_id: null,
    meta_title: "Modbus SCADA Devices Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "modbus-scada-devices-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "MMS Protocol Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of MMS Protocol (IEC 61850-8-1) technology in digital assets.",
    user_id: null,
    meta_title: "MMS Protocol (IEC 61850-8-1) Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "mms-protocol-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Mitsubishi Q PLC Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Mitsubishi Q PLC in digital assets. It identifies the presence and basic information of the Mitsubishi Q Series PLC for network discovery purposes.",
    user_id: null,
    meta_title: "Mitsubishi Q PLC Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "mitsubishi-q-plc-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "KNX Gateway Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc: "This scanner detects the use of KNX Gateway in digital assets.",
    user_id: null,
    meta_title: "KNX Gateway Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "knx-gateway-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "IEC 60870-5-104 Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of IEC 60870-5-104 vulnerability in digital assets. It helps identify the presence of the IEC 60870-5-104 ICS protocol.",
    user_id: null,
    meta_title: "IEC 60870-5-104 Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "iec-60870-5-104-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Tridium Niagara Fox Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Tridium Niagara Fox protocol in digital assets. It provides insights into the system’s configuration and versions, aiding security assessments.",
    user_id: null,
    meta_title: "Tridium Niagara Fox Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "tridium-niagara-fox-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "EtherNet/IP Devices Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of EtherNet/IP Devices on digital assets. It identifies device details such as vendor, product name, serial number, and IP address to facilitate asset discovery and inventory.",
    user_id: null,
    meta_title: "EtherNet/IP Devices Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "ethernet-ip-devices-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "DNP3 Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of DNP3 technology in digital assets. It identifies devices that respond to queries using the DNP3 protocol.",
    user_id: null,
    meta_title: "DNP3 Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "dnp3-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Allen Bradley PLC5 Systems Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Allen Bradley PLC5 Systems in digital assets. It helps identify systems compliant with CSPV4 or AB/Ethernet protocols, facilitating secure monitoring and communication.",
    user_id: null,
    meta_title: "Allen Bradley PLC5 Systems Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "allen-bradley-plc5-systems-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Codesys Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc: "This scanner detects the use of Codesys in digital assets.",
    user_id: null,
    meta_title: "Codesys Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "codesys-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "TCP Services Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of TCP services by capturing and analyzing service banners in digital assets.",
    user_id: null,
    meta_title: "TCP Services Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "tcp-services-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "BACNet Devices Technology Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of BACNet Devices and enumerates device information using standard requests. It helps identify and gather essential information for device management and security.",
    user_id: null,
    meta_title: "BACNet Devices Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "bacnet-devices-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Guardian AST Automatic Tank Gauge Detection Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T15:34:46.560459",
    auto_desc: "",
    protocol_id: null,
    score: 10,
    mini_desc:
      "This scanner detects the use of Guardian AST Automatic Tank Gauge in digital assets.",
    user_id: null,
    meta_title: "Guardian AST Automatic Tank Gauge Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "guardian-ast-automatic-tank-gauge-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "SSL Perfect Forward Secrecy Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:57.533966",
    auto_desc: "",
    protocol_id: 717,
    score: 3,
    mini_desc:
      "Check if your server supports Perfect Forward Secrecy cipher suites. Ensure your server uses ECDHE or DHE with TLS 1.2 or TLS 1.3.",
    user_id: null,
    meta_title: "SSL Perfect Forward Secrecy Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-perfect-forward-secrecy-checker",
    estimate_time: 20,
  },
  {
    name: "SSL TLS_FALLBACK_SCSV Mitigation Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:46.629453",
    auto_desc: "",
    protocol_id: 717,
    score: 3,
    mini_desc:
      "Check your SSL/TLS configuration for TLS_FALLBACK_SCSV vulnerability mitigation. Ensure both client and server support this extension to prevent fallback attacks.",
    user_id: null,
    meta_title: "Online SSL TLS_FALLBACK_SCSV Mitigation Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-tls-fallback-scsv-mitigation-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Renegotiation Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:36.719467",
    auto_desc: "",
    protocol_id: 717,
    score: 5.8,
    mini_desc:
      "Check your SSL/TLS configuration for Renegotiation vulnerability. Ensure your server does not support insecure renegotiation.",
    user_id: null,
    meta_title: "Online SSL Renegotiation Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-renegotiation-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Ticketbleed Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:24.639946",
    auto_desc: "",
    protocol_id: 717,
    score: 7.5,
    mini_desc:
      "Check your SSL/TLS configuration for Ticketbleed vulnerability. Ensure session tickets are properly managed and use modern encryption protocols.",
    user_id: null,
    meta_title: "Online SSL Ticketbleed Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-ticketbleed-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL CCS Injection Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:12.181703",
    auto_desc: "",
    protocol_id: 717,
    score: 6.8,
    mini_desc:
      "Check your SSL/TLS configuration for CCS Injection vulnerability. Ensure your server uses secure cipher suites and follows strict policy controls.",
    user_id: null,
    meta_title: "Online SSL CCS Injection Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-ccs-injection-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL RC4 Cipher Suites Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:01:01.129695",
    auto_desc: "",
    protocol_id: 717,
    score: 5.9,
    mini_desc:
      "Check if your server supports RC4 cipher suites. Disable RC4 cipher suites and use modern encryption methods like AES or ChaCha20 with TLS 1.2 or TLS 1.3.",
    user_id: null,
    meta_title: "Online SSL RC4 Cipher Suites Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-rc4-cipher-suites-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Heartbleed Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:00:47.220666",
    auto_desc: "",
    protocol_id: 717,
    score: 7.5,
    mini_desc:
      "Check your SSL/TLS configuration for Heartbleed vulnerability. Ensure your system is using a patched OpenSSL version.",
    user_id: null,
    meta_title: "Online SSL Heartbleed Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-heartbleed-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Robot Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:00:33.315960",
    auto_desc: "",
    protocol_id: 717,
    score: 7.4,
    mini_desc:
      "Check your SSL/TLS configuration for Robot vulnerability. Ensure your server does not support weak cipher suites like SSL 2.0 or RC4.",
    user_id: null,
    meta_title: "Online SSL Robot Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-robot-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Sweet32 Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:00:22.952206",
    auto_desc: "",
    protocol_id: 717,
    score: 7.5,
    mini_desc:
      "Check your SSL/TLS configuration for Sweet32 vulnerability. Ensure your server uses modern encryption algorithms like AES or ChaCha20.",
    user_id: null,
    meta_title: "Online SSL Sweet32 Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-sweet32-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL DROWN Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:00:12.660495",
    auto_desc: "",
    protocol_id: 717,
    score: 5.9,
    mini_desc:
      "Check your SSL/TLS configuration for DROWN vulnerability. Ensure SSLv2 is disabled and your server uses modern encryption protocols.",
    user_id: null,
    meta_title: "Online SSL DROWN Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-drown-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Logjam Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T11:00:02.976415",
    auto_desc: "",
    protocol_id: 717,
    score: 5.9,
    mini_desc:
      "Check your SSL/TLS configuration for Logjam vulnerability. Ensure your server uses strong Diffie-Hellman key exchange parameters.",
    user_id: null,
    meta_title: "Online SSL Logjam Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-logjam-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Freak Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T10:59:52.885142",
    auto_desc: "",
    protocol_id: 717,
    score: 4.3,
    mini_desc:
      "Check your SSL/TLS configuration for FREAK vulnerability. Ensure your server does not support export-grade RSA keys.",
    user_id: null,
    meta_title: "Online SSL FREAK Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-freak-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Poodle Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T10:59:40.257776",
    auto_desc: "",
    protocol_id: 717,
    score: 4.3,
    mini_desc:
      "Check your SSL/TLS configuration for POODLE vulnerability. Ensure SSL 3.0 is disabled to prevent downgrade attacks.",
    user_id: null,
    meta_title: "Online SSL POODLE Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-poodle-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Lucky13 Vulnerability Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T10:59:29.999799",
    auto_desc: "",
    protocol_id: 717,
    score: 5.9,
    mini_desc:
      "Check your SSL/TLS configuration for Lucky13 vulnerability. Ensure your system uses secure encryption protocols to mitigate timing attacks.",
    user_id: null,
    meta_title: "Online SSL Lucky13 Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-lucky13-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Breach Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T10:59:20.395941",
    auto_desc: "",
    protocol_id: 717,
    score: 5.9,
    mini_desc:
      "Check your SSL/TLS configuration for BREACH vulnerability. Ensure HTTP compression is disabled for sensitive data transfers.",
    user_id: null,
    meta_title: "Online SSL BREACH Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-breach-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "SSL Crime Vulnerability Scanner",
    result_img: "",
    if_api_support: true,
    created_at: "2024-12-17T10:59:09.666235",
    auto_desc: "",
    protocol_id: 717,
    score: 4.3,
    mini_desc:
      "Check your SSL/TLS configuration for CRIME vulnerability. Ensure your server does not use HTTP compression for encrypted sessions.",
    user_id: null,
    meta_title: "Online SSL CRIME Vulnerability Scanner",
    asset_type: "domain,ipv4",
    slug: "ssl-crime-vulnerability-scanner",
    estimate_time: 20,
  },
  {
    name: "SSL Beast Vulnerability Checker",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T10:58:52.124087",
    auto_desc: "",
    protocol_id: 717,
    score: 4.3,
    mini_desc:
      "Test your SSL/TLS configuration for BEAST vulnerability. Ensure you are using a secure version of TLS to protect your encrypted communications.",
    user_id: null,
    meta_title: "Online SSL BEAST Vulnerability Checker",
    asset_type: "domain,ipv4",
    slug: "ssl-beast-vulnerability-checker",
    estimate_time: 20,
  },
  {
    name: "CVE-2024-39887 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T09:57:43.696976",
    auto_desc: "",
    protocol_id: 120,
    score: 4.3,
    mini_desc:
      "CVE-2024-39887 Scanner - SQL Injection vulnerability in Apache Superset",
    user_id: null,
    meta_title:
      "CVE-2024-39887 Scanner - SQL Injection vulnerability in Apache Superset",
    asset_type: "domain,ipv4",
    slug: "apache-superset-sql-injection-CVE-2024-39887",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-8856 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T09:57:22.495568",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-8856 Scanner - Remote Code Execution vulnerability in WP Time Capsule Plugin",
    user_id: null,
    meta_title:
      "CVE-2024-8856 Scanner - Remote Code Execution vulnerability in WP Time Capsule Plugin",
    asset_type: "domain,ipv4",
    slug: "wp-time-capsule-remote-code-execution-cve-2024-8856",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-48307 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T09:56:49.986929",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-48307 Scanner - SQL Injection vulnerability in JeecgBoot",
    user_id: null,
    meta_title:
      "CVE-2024-48307 Scanner - SQL Injection vulnerability in JeecgBoot",
    asset_type: "domain,ipv4",
    slug: "jeecgboot-sql-injection-cve-2024-48307",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-12209 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T09:56:30.807987",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-12209 Scanner - Local File Inclusion vulnerability in WP Umbrella",
    user_id: null,
    meta_title:
      "CVE-2024-12209 Scanner - Local File Inclusion vulnerability in WP Umbrella",
    asset_type: "domain,ipv4",
    slug: "wp-umbrella-local-file-inclusion-cve-2024-12209",
    estimate_time: 10,
  },
  {
    name: "CVE-2017-1000353 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-17T09:56:14.044395",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2017-1000353 Scanner - Java Deserialization vulnerability in Jenkins",
    user_id: null,
    meta_title:
      "CVE-2017-1000353 Scanner - Java Deserialization vulnerability in Jenkins",
    asset_type: "url",
    slug: "jenkins-java-deserialization-cve-2017-1000353",
    estimate_time: 10,
  },
  {
    name: "CVE-2023-37599 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:25:58.441015",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2023-37599 Scanner - Directory Listing vulnerability in Issabel PBX",
    user_id: null,
    meta_title:
      "CVE-2023-37599 Scanner - Directory Listing vulnerability in Issabel PBX",
    asset_type: "url",
    slug: "issabel-pbx-directory-listing-cve-2023-37599",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-10516 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:25:42.098234",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-10516 Scanner - Local File Inclusion (LFI) vulnerability in Swift Performance Lite",
    user_id: null,
    meta_title:
      "CVE-2024-10516 Scanner - Local File Inclusion (LFI) vulnerability in Swift Performance Lite",
    asset_type: "domain,ipv4",
    slug: "swift-performance-lite-local-file-inclusion-cve-2024-10516",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-52433 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-07T14:49:23",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-52433 Scanner - PHP Object Injection vulnerability in My Geo Posts Free",
    user_id: null,
    meta_title:
      "CVE-2024-52433 Scanner - PHP Object Injection vulnerability in My Geo Posts Free",
    asset_type: "domain,ipv4",
    slug: "my-geo-posts-free-php-object-injection-cve-2024-52433",
    estimate_time: 10,
  },
  {
    name: "CVE-2023-46455 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:25:12.743675",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2023-46455 Scanner - Arbitrary File Write vulnerability in GL.iNet",
    user_id: null,
    meta_title:
      "CVE-2023-46455 Scanner - Arbitrary File Write vulnerability in GL.iNet",
    asset_type: "domain,ipv4",
    slug: "gl-inet-arbitrary-file-write-cve-2023-46455",
    estimate_time: 10,
  },
  {
    name: "CVE-2023-50094 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:24:57.816402",
    auto_desc: "",
    protocol_id: 120,
    score: 8.8,
    mini_desc:
      "CVE-2023-50094 Scanner - OS Command Injection vulnerability in reNgine",
    user_id: null,
    meta_title:
      "CVE-2023-50094 Scanner - OS Command Injection vulnerability in reNgine",
    asset_type: "domain,ipv4",
    slug: "rengine-os-command-injection-cve-2023-50094",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-11305 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:24:39.830265",
    auto_desc: "",
    protocol_id: 120,
    score: 6.3,
    mini_desc:
      "CVE-2024-11305 Scanner - SQL Injection vulnerability in Altenergy Power Control Software",
    user_id: null,
    meta_title:
      "CVE-2024-11305 Scanner - SQL Injection vulnerability in Altenergy Power Control Software",
    asset_type: "domain,ipv4",
    slug: "altenergy-power-control-software-sql-injection-cve-2024-11305",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-41713 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:24:22.833827",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-41713 Scanner - Path Traversal vulnerability in Mitel MiCollab",
    user_id: null,
    meta_title:
      "CVE-2024-41713 Scanner - Path Traversal vulnerability in Mitel MiCollab",
    asset_type: "domain,ipv4",
    slug: "mitel-micollab-path-traversal-cve-2024-41713",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-4375 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:23:54.391651",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2022-4375 Scanner - SQL Injection vulnerability in Mingsoft MCMS",
    user_id: null,
    meta_title:
      "CVE-2022-4375 Scanner - SQL Injection vulnerability in Mingsoft MCMS",
    asset_type: "domain,ipv4",
    slug: "mingsoft-mcms-sql-injection-cve-2022-4375",
    estimate_time: 10,
  },
  {
    name: "CVE-2023-3990 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:23:36.428933",
    auto_desc: "",
    protocol_id: 120,
    score: 6.1,
    mini_desc:
      "CVE-2023-3990 Scanner - Cross-Site Scripting (XSS) vulnerability in Mingsoft MCMS",
    user_id: null,
    meta_title:
      "CVE-2023-3990 Scanner - Cross-Site Scripting (XSS) vulnerability in Mingsoft MCMS",
    asset_type: "domain,ipv4",
    slug: "mingsoft-mcms-xss-cve-2023-3990",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-49380 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:23:21.355668",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-49380 Scanner - OS Command Injection vulnerability in Plenti",
    user_id: null,
    meta_title:
      "CVE-2024-49380 Scanner - OS Command Injection vulnerability in Plenti",
    asset_type: "domain,ipv4",
    slug: "plenti-os-command-injection-cve-2024-49380",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-2928 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:23:04.749064",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc: "CVE-2024-2928 Scanner - Path Traversal vulnerability in MLflow",
    user_id: null,
    meta_title:
      "CVE-2024-2928 Scanner - Path Traversal vulnerability in MLflow",
    asset_type: "domain,ipv4",
    slug: "mlflow-path-traversal-cve-2024-2928",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-5334 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-10T15:22:43.397789",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-5334 Scanner - Local File Inclusion vulnerability in Devika AI",
    user_id: null,
    meta_title:
      "CVE-2024-5334 Scanner - Local File Inclusion vulnerability in Devika AI",
    asset_type: "domain,ipv4",
    slug: "devika-ai-lfi-cve-2024-5334",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-3848 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:04:36.869960",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc: "CVE-2024-3848 Scanner - Path Traversal vulnerability in mlflow",
    user_id: null,
    meta_title:
      "CVE-2024-3848 Scanner - Path Traversal vulnerability in mlflow",
    asset_type: "domain,ipv4",
    slug: "mlflow-path-traversal-CVE-2024-3848",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-1483 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:04:17.512766",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc: "CVE-2024-1483 Scanner - Path Traversal vulnerability in mlflow",
    user_id: null,
    meta_title:
      "CVE-2024-1483 Scanner - Path Traversal vulnerability in mlflow",
    asset_type: "domain,ipv4",
    slug: "mlflow-path-traversal-CVE-2024-1483",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-10924 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:03:59.733553",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-10924 Scanner - Authentication Bypass vulnerability in Really Simple Security",
    user_id: null,
    meta_title:
      "CVE-2024-10924 Scanner - Authentication Bypass vulnerability in Really Simple Security",
    asset_type: "domain,ipv4",
    slug: "really-simple-security-authentication-bypass-CVE-2024-10924",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-41800 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:03:43.486638",
    auto_desc: "",
    protocol_id: 120,
    score: 8.7,
    mini_desc:
      "CVE-2022-41800 Scanner - Command Injection vulnerability in F5 BIG-IP Access Policy Manager",
    user_id: null,
    meta_title:
      "CVE-2022-41800 Scanner - Command Injection vulnerability in F5 BIG-IP Access Policy Manager",
    asset_type: "domain,ipv4",
    slug: "f5-big-ip-access-policy-manager-command-injection-CVE-2022-41800",
    estimate_time: 10,
  },
  {
    name: "CVE-2021-34630 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:03:23.159869",
    auto_desc: "",
    protocol_id: 120,
    score: 6.1,
    mini_desc:
      "CVE-2021-34630 Scanner - Cross-Site Scripting (XSS) vulnerability in GTranslate",
    user_id: null,
    meta_title:
      "CVE-2021-34630 Scanner - Cross-Site Scripting (XSS) vulnerability in GTranslate",
    asset_type: "url",
    slug: "gtranslate-cross-site-scripting-cve-2021-34630",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-0250 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:03:08.750582",
    auto_desc: "",
    protocol_id: 120,
    score: 6.1,
    mini_desc:
      "CVE-2022-0250 Scanner - Cross-Site Scripting vulnerability in Redirection for Contact Form 7",
    user_id: null,
    meta_title:
      "CVE-2022-0250 Scanner - Cross-Site Scripting vulnerability in Redirection for Contact Form 7",
    asset_type: "url",
    slug: "redirection-for-contact-form-7-cross-site-scripting-cve-2022-0250",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-24819 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:02:48.645068",
    auto_desc: "",
    protocol_id: 120,
    score: 5.3,
    mini_desc:
      "CVE-2022-24819 Scanner - Information Disclosure vulnerability in XWiki",
    user_id: null,
    meta_title:
      "CVE-2022-24819 Scanner - Information Disclosure vulnerability in XWiki",
    asset_type: "url",
    slug: "xwiki-information-disclosure-cve-2022-24819",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-50498 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:02:32.778646",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-50498 Scanner - Remote Code Execution (RCE) vulnerability in WP Query Console",
    user_id: null,
    meta_title:
      "CVE-2024-50498 Scanner - Remote Code Execution (RCE) vulnerability in WP Query Console",
    asset_type: "domain,ipv4",
    slug: "wp-query-console-remote-code-execution-cve-2024-50498",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-43919 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:02:15.297165",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-43919 Scanner - Missing Authorization vulnerability in Yet Another Related Posts Plugin",
    user_id: null,
    meta_title:
      "CVE-2024-43919 Scanner - Missing Authorization vulnerability in Yet Another Related Posts Plugin",
    asset_type: "url",
    slug: "yet-another-related-posts-plugin-missing-authorization-cve-2024-43919",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-9186 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:01:59.707075",
    auto_desc: "",
    protocol_id: 120,
    score: 8.6,
    mini_desc:
      "CVE-2024-9186 Scanner - SQL Injection vulnerability in FunnelKit Automation By Autonami",
    user_id: null,
    meta_title:
      "CVE-2024-9186 Scanner - SQL Injection vulnerability in FunnelKit Automation By Autonami",
    asset_type: "domain,ipv4",
    slug: "funnelkit-automation-by-autonami-sql-injection-cve-2024-9186",
    estimate_time: 10,
  },
  {
    name: "CVE-2020-24881 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:01:44.402581",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2020-24881 Scanner - Server-Side Request Forgery (SSRF) vulnerability in osTicket",
    user_id: null,
    meta_title:
      "CVE-2020-24881 Scanner - Server-Side Request Forgery (SSRF) vulnerability in osTicket",
    asset_type: "domain,ipv4",
    slug: "osticket-server-side-request-forgery-cve-2020-24881",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-51482 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:01:29.377490",
    auto_desc: "",
    protocol_id: 120,
    score: 9.9,
    mini_desc:
      "CVE-2024-51482 Scanner - SQL Injection vulnerability in ZoneMinder",
    user_id: null,
    meta_title:
      "CVE-2024-51482 Scanner - SQL Injection vulnerability in ZoneMinder",
    asset_type: "domain,ipv4",
    slug: "zoneminder-sql-injection-cve-2024-51482",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-2130 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:01:11.042522",
    auto_desc: "",
    protocol_id: 120,
    score: 6.1,
    mini_desc:
      "CVE-2022-2130 Scanner - Cross-Site Scripting (XSS) vulnerability in Microweber",
    user_id: null,
    meta_title:
      "CVE-2022-2130 Scanner - Cross-Site Scripting (XSS) vulnerability in Microweber",
    asset_type: "url",
    slug: "microweber-cross-site-scripting-cve-2022-2130",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-9935 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:00:55.088112",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-9935 Scanner - Arbitrary File Download vulnerability in PDF Generator Addon for Elementor Page Builder",
    user_id: null,
    meta_title:
      "CVE-2024-9935 Scanner - Arbitrary File Download vulnerability in PDF Generator Addon for Elementor Page Builder",
    asset_type: "domain,ipv4",
    slug: "pdf-generator-addon-for-elementor-page-builder-arbitrary-file-download-cve-2024-9935",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-46938 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-12-03T22:00:39.958693",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-46938 Scanner - Arbitrary File Read vulnerability in Sitecore Experience Platform",
    user_id: null,
    meta_title:
      "CVE-2024-46938 Scanner - Arbitrary File Read vulnerability in Sitecore Experience Platform",
    asset_type: "domain,ipv4",
    slug: "sitecore-experience-platform-arbitrary-file-read-cve-2024-46938",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-42640 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:44:27.438246",
    auto_desc: "",
    protocol_id: 120,
    score: 10,
    mini_desc:
      "CVE-2024-42640 scanner - Remote Code Execution (RCE) vulnerability in Angular Base64 Upload",
    user_id: null,
    meta_title:
      "CVE-2024-42640 scanner - Remote Code Execution (RCE) vulnerability in Angular Base64 Upload",
    asset_type: "domain,ipv4",
    slug: "angular-base64-upload-remote-code-execution-cve-2024-42640",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-9474 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:44:14.645433",
    auto_desc: "",
    protocol_id: 120,
    score: 7.2,
    mini_desc:
      "CVE-2024-9474 Scanner - Command Injection vulnerability in PAN-OS Management Web Interface",
    user_id: null,
    meta_title:
      "CVE-2024-9474 Scanner - Command Injection vulnerability in PAN-OS Management Web Interface",
    asset_type: "domain,ipv4",
    slug: "pan-os-management-web-interface-command-injection-cve-2024-9474",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-38653 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:43:48.581850",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2024-38653 scanner - XML External Entity (XXE) vulnerability in Ivanti Avalanche SmartDeviceServer",
    user_id: null,
    meta_title:
      "CVE-2024-38653 scanner - XML External Entity (XXE) vulnerability in Ivanti Avalanche SmartDeviceServer",
    asset_type: "domain,ipv4",
    slug: "ivanti-avalanche-smartdeviceserver-xxe-cve-2024-38653",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-0012 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:44:47.932678",
    auto_desc: "",
    protocol_id: 120,
    score: 9.8,
    mini_desc:
      "CVE-2024-0012 scanner - Authentication Bypass vulnerability in PAN-OS Management Web Interface",
    user_id: null,
    meta_title:
      "CVE-2024-0012 scanner - Authentication Bypass vulnerability in PAN-OS Management Web Interface",
    asset_type: "domain,ipv4",
    slug: "pan-os-management-web-interface-authentication-bypass-cve-2024-0012",
    estimate_time: 10,
  },
  {
    name: "Backuply Technology Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:52:51.398014",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc: "This scanner detects the use of Backuply in digital assets.",
    user_id: null,
    meta_title: "Backuply Technology Detection Scanner",
    asset_type: "url",
    slug: "backuply-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-44356 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:45:17.548212",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2022-44356 scanner - Information Disclosure vulnerability in WAVLINK Quantum D4G (WL-WN531G3)",
    user_id: null,
    meta_title:
      "CVE-2022-44356 scanner - Information Disclosure vulnerability in WAVLINK Quantum D4G (WL-WN531G3)",
    asset_type: "url",
    slug: "wavlink-quantum-d4g-information-disclosure-cve-2022-44356",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-48166 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:45:31.070328",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2022-48166 Scanner - Information Disclosure vulnerability in Wavlink WL-WN530HG4 Firmware",
    user_id: null,
    meta_title:
      "CVE-2022-48166 Scanner - Information Disclosure vulnerability in Wavlink WL-WN530HG4 Firmware",
    asset_type: "url",
    slug: "wavlink-wl-wn530hg4-firmware-information-disclosure-cve-2022-48166",
    estimate_time: 10,
  },
  {
    name: "CVE-2022-48164 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-20T06:45:49.643582",
    auto_desc: "",
    protocol_id: 120,
    score: 7.5,
    mini_desc:
      "CVE-2022-48164 scanner - Information Disclosure vulnerability in Wavlink WL-WN533A8 Firmware",
    user_id: null,
    meta_title:
      "CVE-2022-48164 scanner - Information Disclosure vulnerability in Wavlink WL-WN533A8 Firmware",
    asset_type: "url",
    slug: "wavlink-information-disclosure-cve-2022-48164",
    estimate_time: 10,
  },
  {
    name: "Fortinet FGFM Protocol Technology Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:53:41.792753",
    auto_desc: "",
    protocol_id: 120,
    score: 1,
    mini_desc:
      "This scanner detects the use of Fortinet FGFM protocol in digital assets. It accurately identifies deployments of the FortiGate to FortiManager protocol to support network security assessments.",
    user_id: null,
    meta_title: "Fortinet FGFM Protocol Technology Detection Scanner",
    asset_type: "domain,ipv4",
    slug: "fortinet-fgfm-protocol-technology-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "CVE-2024-51483 Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:54:47.493765",
    auto_desc: "",
    protocol_id: 120,
    score: 5,
    mini_desc:
      "CVE-2024-51483 Scanner - Path Traversal vulnerability in Changedetection.io",
    user_id: null,
    meta_title:
      "CVE-2024-51483 Scanner - Path Traversal vulnerability in Changedetection.io",
    asset_type: "domain,ipv4",
    slug: "changedetection-io-path-traversal-cve-2024-51483",
    estimate_time: 10,
  },
  {
    name: "Alfresco Content App Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:55:41.994183",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc:
      "This scanner detects the use of Alfresco Content App panel in digital assets.",
    user_id: null,
    meta_title: "Alfresco Content App Panel Detection Scanner",
    asset_type: "url",
    slug: "alfresco-content-app-panel-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Akuiteo Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:56:52.517685",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc:
      "This scanner detects the use of Akuiteo in digital assets. It helps identify instances of Akuiteo login panels for tracking and management purposes.",
    user_id: null,
    meta_title: "Akuiteo Panel Detection Scanner",
    asset_type: "url",
    slug: "akuiteo-panel-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "AlternC Desktop Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T12:59:36.338250",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc:
      "This scanner detects the use of AlternC Desktop Panel in digital assets. It identifies instances of the AlternC control panel to help assess if correct settings are applied.",
    user_id: null,
    meta_title: "AlternC Desktop Panel Detection Scanner",
    asset_type: "url",
    slug: "alternc-desktop-panel-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Thruk Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T13:00:14.194194",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc: "This scanner detects the use of Thruk in digital assets.",
    user_id: null,
    meta_title: "Thruk Panel Detection Scanner",
    asset_type: "url",
    slug: "thruk-panel-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "OPNsense Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T13:00:49.245747",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc:
      "This scanner detects the use of OPNsense panel in digital assets.",
    user_id: null,
    meta_title: "OPNsense Panel Detection Scanner",
    asset_type: "url",
    slug: "opnsense-panel-detection-scanner",
    estimate_time: 10,
  },
  {
    name: "Alamos GmbH Panel Detection Scanner",
    result_img: null,
    if_api_support: true,
    created_at: "2024-11-26T13:01:23.389562",
    auto_desc: "",
    protocol_id: 120,
    score: 5.5,
    mini_desc:
      "This scanner detects the use of Alamos GmbH Panel in digital assets.",
    user_id: null,
    meta_title: "Alamos GmbH Panel Detection Scanner",
    asset_type: "url",
    slug: "alamos-gmbh-panel-detection-scanner",
    estimate_time: 10,
  },
];
